# Generated by Django 4.2.1 on 2025-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_alter_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.CharField(max_length=50, verbose_name='The address'),
        ),
    ]
