# Generated by Django 4.2.1 on 2025-03-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0003_alter_clients_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='number',
            new_name='num',
        ),
    ]
